
spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=User;instanceName=SQLEXPRESS;encrypt=true;trustServerCertificate=true;
    username: sa
    password: password_123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      registerWithEureka: true
      fetchRegistry: true
      defaultZone: http://localhost:8079/eureka/

  instance:
    hostname: localhost


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true

  endpoint:
    health:
      show-details: always



resilience4j:
  circuitbreaker:
    instances:
      userService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        permittedNumberOfCallsInHalfOpenState:   3
        slidingWindowType: TIME_BASED


microservices:
  endpoint:
    search:
      doctorSpeciality:
        findBySpecialization: "http://localhost:9090/search/searchspeciality/"

      hospitalSearch:
        findByHospitalId: "http://localhost:9090/search/searchhospitalById/"

        findByHospitalName: "http://localhost:9090/search/searchhospital/"

    booking:
      save: "http://localhost:9090/book/booking/save"
